### ISSUE TITLE
How to fix duplicate Tabs issue?

### ISSUE THREAD

**Issue by tellfa** [egemenmede/etiyabadgetab#2] opened 2017-07-12 14:46 UTC
Hi, thanks for this library.
i want use you library but when run application show me duplicate tabs. such as below image
![quickmemo _2017-07-12-19-11-56](https://user-images.githubusercontent.com/10583945/28123562-8339797a-6736-11e7-91e4-f56ee4a78964.png)

How can i fix it? i really need your library, please help me

**Comment by egemenmede** [comment] 2017-07-12 15:45
Hi, it's good to hear yuu like it. Thank you

It s not possible to have issue like this. You probably made a configurational mistake. Can you check your code again. If you could not figure out the real problem you can show me the code snippet.
Maybe i can help.

**Comment by tellfa** [comment] 2017-07-12 15:47
Do you have Team viewer? can you connect my pc ? 
please i really need your help. please

**Comment by tellfa** [comment] 2017-07-12 16:03
i will wait you?
can you connect my PC ?

**Comment by egemenmede** [comment] 2017-07-13 04:51
No, I can not connect to your computer. But you can share the code snippet here.

**Comment by tellfa** [comment] 2017-07-13 04:56
Please see my codes in below, i share all of codes from activity.
Please see and help me, i really need you help for this library. Thanks.
**My codes :**
```
public class FullSearch extends AppCompatActivity {

    @BindView(R.id.fullSearch_tabLayout)
    BadgeTabLayout fullSearch_tabLayout;
    @BindView(R.id.fullSearch_ViewPager)
    ViewPager fullSearch_ViewPager;
    @BindView(R.id.toolbarTitleTxt)
    TextView toolbarTitleTxt;
    @BindView(R.id.fullSearch_LoadLay)
    RelativeLayout fullSearch_LoadLay;
    @BindView(R.id.fullSearch_ReloadLay)
    RelativeLayout fullSearch_ReloadLay;
    @BindView(R.id.fullSearch_NoNet)
    RelativeLayout fullSearch_NoNet;
    private Context context;
    private Bundle bundle;
    private String fullSearchText;
    private List<Movie> movieList = new ArrayList<>();
    private List<Series> seriesList = new ArrayList<>();
    private List<Celebrity> celebrityList = new ArrayList<>();
    private List<User> userList = new ArrayList<>();
    private List<Series> episodeList = new ArrayList<>();
    private int movieCount, serieCount, episodesCount, celebritiesCount, usersCount;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_full_search);

        // Initialize
        ButterKnife.bind(this);
        context = this;
        bundle = getIntent().getExtras();
        fullSearchText = bundle.getString(ExtraContains.FULL_SEARCH_TEXT.name());

        toolbarTitleTxt.setText(fullSearchText);

        // set viewPager to tabLayout
        fullSearch_tabLayout.setupWithViewPager(fullSearch_ViewPager);

        // customize tab layout
        fullSearch_tabLayout.setSelectedTabIndicatorColor(context.getResources().getColor(R.color.colorAccent));
        fullSearch_tabLayout.setSelectedTabIndicatorHeight(5);
        fullSearch_tabLayout.setTabMode(TabLayout.MODE_SCROLLABLE);
        fullSearch_tabLayout.setTabGravity(TabLayout.GRAVITY_FILL);

        fullSearch_LoadLay.setVisibility(View.GONE);

        getData();
    }

    @Override
    protected void onResume() {
        super.onResume();
        //checkNet();
        //fullSearch_LoadLay.setVisibility(View.GONE);
    }

    private void getData() {
        FullSearchSendData sendData = new FullSearchSendData();
        sendData.setKey(fullSearchText);
        sendData.setLoadImages(true);
        sendData.setSearchInCelebrities(true);
        sendData.setSearchInMovies(true);
        sendData.setSearchInSeries(true);
        sendData.setSearchInEpisodes(true);
        sendData.setSearchInUsers(true);
        sendData.setPageIndex(1);
        sendData.setPageSize(10);
        sendData.setMaxDistance(1);

        fullSearch_LoadLay.setVisibility(View.VISIBLE);

        InterfaceApi api = ApiClient.getClient().create(InterfaceApi.class);
        Call<FullSearchResponse> call = api.getFullSearch(sendData);

        call.enqueue(new Callback<FullSearchResponse>() {
            @Override
            public void onResponse(Call<FullSearchResponse> call, Response<FullSearchResponse> response) {
                FullSearchResponse searchResponse = response.body();
                if (searchResponse.getData().getCelebritiesCount() > 0) {
                    celebritiesCount = searchResponse.getData().getCelebritiesCount();
                    celebrityList.clear();
                    celebrityList.addAll(searchResponse.getData().getCelebrities());
                }
                if (searchResponse.getData().getMoviesCount() > 0) {
                    movieCount = searchResponse.getData().getMoviesCount();
                    movieList.clear();
                    movieList.addAll(searchResponse.getData().getMovies());
                }
                if (searchResponse.getData().getSeriesCount() > 0) {
                    serieCount = searchResponse.getData().getSeriesCount();
                    seriesList.clear();
                    seriesList.addAll(searchResponse.getData().getSeries());
                }
                if (searchResponse.getData().getUsersCount() > 0) {
                    usersCount = searchResponse.getData().getUsersCount();
                    userList.clear();
                    userList.addAll(searchResponse.getData().getUsers());
                }

                setupViewPager(fullSearch_ViewPager);
                setupTabs();

                fullSearch_LoadLay.setVisibility(View.GONE);
            }

            @Override
            public void onFailure(Call<FullSearchResponse> call, Throwable t) {
                fullSearch_LoadLay.setVisibility(View.GONE);
                fullSearch_ReloadLay.setVisibility(View.VISIBLE);
            }
        });
    }

    private void setupTabs() {
        if (celebritiesCount > 0) {
            fullSearch_tabLayout.addTab(fullSearch_tabLayout.newTab());
            //fullSearch_tabLayout.selectEtiyaBadgeTab(fullSearch_tabLayout.getTabCount() - 1)
            fullSearch_tabLayout.selectEtiyaBadgeTab(0)
                    .tabTitle("Celebrities")
                    .tabTitleColor(R.color.white)
                    .tabBadge(true)
                    .tabBadgeCount(celebritiesCount)
                    .tabBadgeCountMore(false)
                    .tabBadgeBgColor(R.color.colorAccent)
                    .tabBadgeTextColor(R.color.white)
                    .tabBadgeStroke(2, R.color.white)
                    .tabBadgeCornerRadius(15)
                    .createEtiyaBadgeTab();
        }
        if (movieCount > 0) {
            fullSearch_tabLayout.addTab(fullSearch_tabLayout.newTab());
            //fullSearch_tabLayout.selectEtiyaBadgeTab(fullSearch_tabLayout.getTabCount() - 1)
            fullSearch_tabLayout.selectEtiyaBadgeTab(1)
                    .tabTitle("Movies")
                    .tabTitleColor(R.color.white)
                    .tabBadge(true)
                    .tabBadgeCount(movieCount)
                    .tabBadgeCountMore(false)
                    .tabBadgeBgColor(R.color.colorAccent)
                    .tabBadgeTextColor(R.color.white)
                    .tabBadgeStroke(2, R.color.white)
                    .tabBadgeCornerRadius(15)
                    .createEtiyaBadgeTab();
        }
        if (serieCount > 0) {
            fullSearch_tabLayout.addTab(fullSearch_tabLayout.newTab());
            //fullSearch_tabLayout.selectEtiyaBadgeTab(fullSearch_tabLayout.getTabCount() - 1)
            fullSearch_tabLayout.selectEtiyaBadgeTab(2)
                    .tabTitle("Series")
                    .tabTitleColor(R.color.white)
                    .tabBadge(true)
                    .tabBadgeCount(serieCount)
                    .tabBadgeCountMore(false)
                    .tabBadgeBgColor(R.color.colorAccent)
                    .tabBadgeTextColor(R.color.white)
                    .tabBadgeStroke(2, R.color.white)
                    .tabBadgeCornerRadius(15)
                    .createEtiyaBadgeTab();
        }
        if (usersCount > 0) {
            fullSearch_tabLayout.addTab(fullSearch_tabLayout.newTab());
            //fullSearch_tabLayout.selectEtiyaBadgeTab(fullSearch_tabLayout.getTabCount()-1)
            fullSearch_tabLayout.selectEtiyaBadgeTab(3)
                    .tabTitle("Users")
                    .tabTitleColor(R.color.white)
                    .tabBadge(true)
                    .tabBadgeCount(usersCount)
                    .tabBadgeCountMore(false)
                    .tabBadgeBgColor(R.color.colorAccent)
                    .tabBadgeTextColor(R.color.white)
                    .tabBadgeStroke(2, R.color.white)
                    .tabBadgeCornerRadius(15)
                    .createEtiyaBadgeTab();
        }
    }

    private void setupViewPager(ViewPager viewPager) {

        ViewPagerAdapter adapter = new ViewPagerAdapter(getSupportFragmentManager());
        if (celebritiesCount > 0) {
            adapter.addFrag(FullSearchCelebritiesFragment.getInstance(celebrityList, celebritiesCount, fullSearchText), "Celebrities");
        }
        if (movieCount > 0) {
            adapter.addFrag(FullSearchMovieFragment.getInstance(movieList, movieCount, fullSearchText), "Movies");
        }
        if (serieCount > 0) {
            adapter.addFrag(FullSearchSeriesFragment.getInstance(seriesList, serieCount, fullSearchText), "Series");
        }
        if (usersCount > 0) {
            adapter.addFrag(FullSearchUsersFragment.getInstance(userList, usersCount, fullSearchText), "Users");
        }
        viewPager.setAdapter(adapter);
    }

    class ViewPagerAdapter extends FragmentPagerAdapter {
        private final List<Fragment> mFragmentList = new ArrayList<>();
        private final List<String> mFragmentTitleList = new ArrayList<>();

        ViewPagerAdapter(FragmentManager manager) {
            super(manager);
        }

        @Override
        public Fragment getItem(int position) {
            return mFragmentList.get(position);
        }

        @Override
        public int getCount() {
            return mFragmentList.size();
        }

        public void addFrag(Fragment fragment, String title) {
            mFragmentList.add(fragment);
            mFragmentTitleList.add(title);
        }

        @Override
        public CharSequence getPageTitle(int position) {
            return mFragmentTitleList.get(position);
        }
    } 
```

I will wait you  ❤️

**Comment by egemenmede** [comment] 2017-07-13 07:01
First of all it is not a mistake with this plugin. As far as I see, you are sending more data than tabs you create. For this reason sendData.setSearchInEpisodes (true); Value sendData.setSearchInEpisodes (false); Would you change it and try?

**Comment by tellfa** [comment] 2017-07-13 07:08
I set sendData.setSearchInEpisodes(false); , and show again such as above image! create duplicate tabs! such as above image

**Comment by egemenmede** [comment] 2017-07-13 07:14
Hmmm. I understand the problem. Would you remove control codes like if (celebritiesCount> 0) from both setupViewPager and setupTabs?

While creating Tabs

fullsearch_tablayout.selectetiyabadgetab (0)

0,1,2,3. However, if the elebentsCount> 0 condition is not met, the sorting is broken.

What do you need to do?

You need to increase the tab order in the places where selectEtiyaBadgeTab (0) is done in the condition that the condition is performed. Ok?

**Comment by tellfa** [comment] 2017-07-13 07:16
Can you send me code with my above codes? please . 
i am amateur 😢 please

**Comment by egemenmede** [comment] 2017-07-13 07:16
public class FullSearch extends AppCompatActivity {

    @BindView(R.id.fullSearch_tabLayout)
    BadgeTabLayout fullSearch_tabLayout;
    @BindView(R.id.fullSearch_ViewPager)
    ViewPager fullSearch_ViewPager;
    @BindView(R.id.toolbarTitleTxt)
    TextView toolbarTitleTxt;
    @BindView(R.id.fullSearch_LoadLay)
    RelativeLayout fullSearch_LoadLay;
    @BindView(R.id.fullSearch_ReloadLay)
    RelativeLayout fullSearch_ReloadLay;
    @BindView(R.id.fullSearch_NoNet)
    RelativeLayout fullSearch_NoNet;
    private Context context;
    private Bundle bundle;
    private String fullSearchText;
    private List<Movie> movieList = new ArrayList<>();
    private List<Series> seriesList = new ArrayList<>();
    private List<Celebrity> celebrityList = new ArrayList<>();
    private List<User> userList = new ArrayList<>();
    private List<Series> episodeList = new ArrayList<>();
    private int movieCount, serieCount, episodesCount, celebritiesCount, usersCount;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_full_search);

        // Initialize
        ButterKnife.bind(this);
        context = this;
        bundle = getIntent().getExtras();
        fullSearchText = bundle.getString(ExtraContains.FULL_SEARCH_TEXT.name());

        toolbarTitleTxt.setText(fullSearchText);

        // set viewPager to tabLayout
        fullSearch_tabLayout.setupWithViewPager(fullSearch_ViewPager);

        // customize tab layout
        fullSearch_tabLayout.setSelectedTabIndicatorColor(context.getResources().getColor(R.color.colorAccent));
        fullSearch_tabLayout.setSelectedTabIndicatorHeight(5);
        fullSearch_tabLayout.setTabMode(TabLayout.MODE_SCROLLABLE);
        fullSearch_tabLayout.setTabGravity(TabLayout.GRAVITY_FILL);

        fullSearch_LoadLay.setVisibility(View.GONE);

        getData();
    }

    @Override
    protected void onResume() {
        super.onResume();
        //checkNet();
        //fullSearch_LoadLay.setVisibility(View.GONE);
    }

    private void getData() {
        FullSearchSendData sendData = new FullSearchSendData();
        sendData.setKey(fullSearchText);
        sendData.setLoadImages(true);
        sendData.setSearchInCelebrities(true);
        sendData.setSearchInMovies(true);
        sendData.setSearchInSeries(true);
        sendData.setSearchInEpisodes(true);
        sendData.setSearchInUsers(true);
        sendData.setPageIndex(1);
        sendData.setPageSize(10);
        sendData.setMaxDistance(1);

        fullSearch_LoadLay.setVisibility(View.VISIBLE);

        InterfaceApi api = ApiClient.getClient().create(InterfaceApi.class);
        Call<FullSearchResponse> call = api.getFullSearch(sendData);

        call.enqueue(new Callback<FullSearchResponse>() {
            @Override
            public void onResponse(Call<FullSearchResponse> call, Response<FullSearchResponse> response) {
                FullSearchResponse searchResponse = response.body();
                if (searchResponse.getData().getCelebritiesCount() > 0) {
                    celebritiesCount = searchResponse.getData().getCelebritiesCount();
                    celebrityList.clear();
                    celebrityList.addAll(searchResponse.getData().getCelebrities());
                }
                if (searchResponse.getData().getMoviesCount() > 0) {
                    movieCount = searchResponse.getData().getMoviesCount();
                    movieList.clear();
                    movieList.addAll(searchResponse.getData().getMovies());
                }
                if (searchResponse.getData().getSeriesCount() > 0) {
                    serieCount = searchResponse.getData().getSeriesCount();
                    seriesList.clear();
                    seriesList.addAll(searchResponse.getData().getSeries());
                }
                if (searchResponse.getData().getUsersCount() > 0) {
                    usersCount = searchResponse.getData().getUsersCount();
                    userList.clear();
                    userList.addAll(searchResponse.getData().getUsers());
                }

                setupViewPager(fullSearch_ViewPager);
                setupTabs();

                fullSearch_LoadLay.setVisibility(View.GONE);
            }

            @Override
            public void onFailure(Call<FullSearchResponse> call, Throwable t) {
                fullSearch_LoadLay.setVisibility(View.GONE);
                fullSearch_ReloadLay.setVisibility(View.VISIBLE);
            }
        });
    }

    private void setupTabs() {
        
            fullSearch_tabLayout.addTab(fullSearch_tabLayout.newTab());
            //fullSearch_tabLayout.selectEtiyaBadgeTab(fullSearch_tabLayout.getTabCount() - 1)
            fullSearch_tabLayout.selectEtiyaBadgeTab(0)
                    .tabTitle("Celebrities")
                    .tabTitleColor(R.color.white)
                    .tabBadge(true)
                    .tabBadgeCount(celebritiesCount)
                    .tabBadgeCountMore(false)
                    .tabBadgeBgColor(R.color.colorAccent)
                    .tabBadgeTextColor(R.color.white)
                    .tabBadgeStroke(2, R.color.white)
                    .tabBadgeCornerRadius(15)
                    .createEtiyaBadgeTab();
        
            fullSearch_tabLayout.addTab(fullSearch_tabLayout.newTab());
            //fullSearch_tabLayout.selectEtiyaBadgeTab(fullSearch_tabLayout.getTabCount() - 1)
            fullSearch_tabLayout.selectEtiyaBadgeTab(1)
                    .tabTitle("Movies")
                    .tabTitleColor(R.color.white)
                    .tabBadge(true)
                    .tabBadgeCount(movieCount)
                    .tabBadgeCountMore(false)
                    .tabBadgeBgColor(R.color.colorAccent)
                    .tabBadgeTextColor(R.color.white)
                    .tabBadgeStroke(2, R.color.white)
                    .tabBadgeCornerRadius(15)
                    .createEtiyaBadgeTab();
        
            fullSearch_tabLayout.addTab(fullSearch_tabLayout.newTab());
            //fullSearch_tabLayout.selectEtiyaBadgeTab(fullSearch_tabLayout.getTabCount() - 1)
            fullSearch_tabLayout.selectEtiyaBadgeTab(2)
                    .tabTitle("Series")
                    .tabTitleColor(R.color.white)
                    .tabBadge(true)
                    .tabBadgeCount(serieCount)
                    .tabBadgeCountMore(false)
                    .tabBadgeBgColor(R.color.colorAccent)
                    .tabBadgeTextColor(R.color.white)
                    .tabBadgeStroke(2, R.color.white)
                    .tabBadgeCornerRadius(15)
                    .createEtiyaBadgeTab();
        
            fullSearch_tabLayout.addTab(fullSearch_tabLayout.newTab());
            //fullSearch_tabLayout.selectEtiyaBadgeTab(fullSearch_tabLayout.getTabCount()-1)
            fullSearch_tabLayout.selectEtiyaBadgeTab(3)
                    .tabTitle("Users")
                    .tabTitleColor(R.color.white)
                    .tabBadge(true)
                    .tabBadgeCount(usersCount)
                    .tabBadgeCountMore(false)
                    .tabBadgeBgColor(R.color.colorAccent)
                    .tabBadgeTextColor(R.color.white)
                    .tabBadgeStroke(2, R.color.white)
                    .tabBadgeCornerRadius(15)
                    .createEtiyaBadgeTab();
        
    }

    private void setupViewPager(ViewPager viewPager) {

        ViewPagerAdapter adapter = new ViewPagerAdapter(getSupportFragmentManager());

            adapter.addFrag(FullSearchCelebritiesFragment.getInstance(celebrityList, celebritiesCount, fullSearchText), "Celebrities");

            adapter.addFrag(FullSearchMovieFragment.getInstance(movieList, movieCount, fullSearchText), "Movies");

            adapter.addFrag(FullSearchSeriesFragment.getInstance(seriesList, serieCount, fullSearchText), "Series");

            adapter.addFrag(FullSearchUsersFragment.getInstance(userList, usersCount, fullSearchText), "Users");

        viewPager.setAdapter(adapter);
    }

    class ViewPagerAdapter extends FragmentPagerAdapter {
        private final List<Fragment> mFragmentList = new ArrayList<>();
        private final List<String> mFragmentTitleList = new ArrayList<>();

        ViewPagerAdapter(FragmentManager manager) {
            super(manager);
        }

        @Override
        public Fragment getItem(int position) {
            return mFragmentList.get(position);
        }

        @Override
        public int getCount() {
            return mFragmentList.size();
        }

        public void addFrag(Fragment fragment, String title) {
            mFragmentList.add(fragment);
            mFragmentTitleList.add(title);
        }

        @Override
        public CharSequence getPageTitle(int position) {
            return mFragmentTitleList.get(position);
        }
    }

**Comment by egemenmede** [comment] 2017-07-13 07:18
But with this code example we have only removed the conditions. You need to code yourself to work as you want. I'm closing the issue because the problem is not related to the plugin.

**Comment by tellfa** [comment] 2017-07-13 07:19
your code always show tabs, but i want when data.size < 0 not show this tab!
just show data.size > 0 tabs!

**Closed as completed by egemenmede** 2017-07-13 07:18 UTC

**Comment by egemenmede** [comment] 2017-07-13 07:22
Evet doğru. Ama bu plugin ile ilgili değil. Sizin bunun için kontrol kodu yazmanız gerekiyor.

**Comment by egemenmede** [comment] 2017-07-13 07:22
Yes true. But this is not about the plugin. You need to write the control code for this.
